from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import shutil
import subprocess
import sys
import textwrap
import uuid
from pathlib import Path

from cryptography.fernet import Fernet


ROOT = Path(__file__).resolve().parent
SCRIPTS = ROOT / "scripts"
DEFAULT_OUT = ROOT / "dist" / "sd-webui-agent-encrypted"

PROTECTED_MODULES = [
    "agent",
    "agent_config",
    "agent_tools",
    "agent_tools_registry",
    "agent_prompts",
    "canva_mcp",
]


def machine_secret() -> str:
    """Return a stable local-machine secret for this build.

    This is copy protection, not perfect DRM: the protected package is bound to
    this Windows/user environment by default.
    """
    parts = [os.environ.get("COMPUTERNAME", ""), os.environ.get("USERNAME", ""), str(uuid.getnode())]
    try:
        out = subprocess.check_output(
            ["reg", "query", r"HKLM\SOFTWARE\Microsoft\Cryptography", "/v", "MachineGuid"],
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=3,
        )
        parts.append(out.strip())
    except Exception:
        pass
    return "|".join(parts)


def derive_fernet_key(secret: str, salt: bytes) -> bytes:
    digest = hashlib.pbkdf2_hmac("sha256", secret.encode("utf-8"), salt, 240_000, dklen=32)
    return base64.urlsafe_b64encode(digest)


def loader_source(module_name: str) -> str:
    package_name = f"{module_name}.agentpkg"
    return textwrap.dedent(
        f'''
        # Protected loader generated by protect_agent_local.py.
        # The real module body is encrypted in {package_name}.
        from __future__ import annotations

        import base64
        import hashlib
        import json
        import os
        import subprocess
        import uuid
        from pathlib import Path

        from cryptography.fernet import Fernet, InvalidToken


        def _machine_secret() -> str:
            parts = [os.environ.get("COMPUTERNAME", ""), os.environ.get("USERNAME", ""), str(uuid.getnode())]
            try:
                out = subprocess.check_output(
                    ["reg", "query", r"HKLM\\SOFTWARE\\Microsoft\\Cryptography", "/v", "MachineGuid"],
                    stderr=subprocess.DEVNULL,
                    text=True,
                    timeout=3,
                )
                parts.append(out.strip())
            except Exception:
                pass
            return "|".join(parts)


        def _derive_key(secret: str, salt: bytes) -> bytes:
            digest = hashlib.pbkdf2_hmac("sha256", secret.encode("utf-8"), salt, 240_000, dklen=32)
            return base64.urlsafe_b64encode(digest)


        def _load() -> None:
            payload_path = Path(__file__).with_name("{package_name}")
            payload = json.loads(payload_path.read_text(encoding="utf-8"))
            salt = base64.b64decode(payload["salt"])
            token = payload["token"].encode("ascii")
            try:
                source = Fernet(_derive_key(_machine_secret(), salt)).decrypt(token).decode("utf-8")
            except InvalidToken as exc:
                raise RuntimeError(
                    "Agent protected module cannot be decrypted on this machine. "
                    "Rebuild the protected package on this WebUI computer."
                ) from exc
            code = compile(source, str(payload_path), "exec")
            exec(code, globals(), globals())


        _load()
        '''
    ).lstrip()


def copy_tree_without_cache(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    ignore = shutil.ignore_patterns("__pycache__", "*.pyc", "dist", "see-through", "workspace")
    shutil.copytree(src, dst, ignore=ignore)


def write_public_config(out: Path) -> None:
    cfg_path = out / "agent_config.json"
    cfg = {}
    if cfg_path.exists():
        try:
            cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
        except Exception:
            cfg = {}
    for key in ("api_key", "image_api_key"):
        cfg[key] = ""
    cfg_path.write_text(json.dumps(cfg, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def build(out: Path) -> None:
    if not (SCRIPTS / "agent.py").is_file():
        raise SystemExit("scripts/agent.py not found")
    copy_tree_without_cache(ROOT, out)
    write_public_config(out)

    secret = machine_secret()
    encrypted_dir = out / "scripts"
    for module_name in PROTECTED_MODULES:
        source_path = SCRIPTS / f"{module_name}.py"
        if not source_path.is_file():
            continue
        salt = os.urandom(16)
        token = Fernet(derive_fernet_key(secret, salt)).encrypt(source_path.read_bytes()).decode("ascii")
        payload = {
            "format": "forge-agent-local-fernet-v1",
            "module": module_name,
            "salt": base64.b64encode(salt).decode("ascii"),
            "token": token,
        }
        (encrypted_dir / f"{module_name}.agentpkg").write_text(
            json.dumps(payload, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        (encrypted_dir / f"{module_name}.py").write_text(loader_source(module_name), encoding="utf-8")

    readme = """# Encrypted sd-webui-agent build

This is a machine-bound protected build.

- `scripts/agent.py` stays readable because WebUI must import an entry file.
- Core modules are encrypted as `.agentpkg` files.
- The small `.py` files beside them are loaders.
- API keys are intentionally blank in `agent_config.json`.

Build again on the target WebUI machine if decryption fails.
"""
    (out / "ENCRYPTED_BUILD_README.md").write_text(readme, encoding="utf-8")
    print(f"Encrypted Agent build created: {out}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build machine-bound encrypted sd-webui-agent package.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Output plugin directory")
    args = parser.parse_args()
    build(Path(args.out).resolve())


if __name__ == "__main__":
    main()
