param(
    [string]$Python = "python",
    [string]$OutputDir = "dist\sd-webui-agent-protected"
)

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$Scripts = Join-Path $Root "scripts"
$Out = Join-Path $Root $OutputDir
$OutScripts = Join-Path $Out "scripts"

Write-Host "[Agent Protect] Source: $Root"
Write-Host "[Agent Protect] Output: $Out"

$pyarmor = & $Python -m pyarmor -v 2>$null
if ($LASTEXITCODE -ne 0) {
    throw "PyArmor is not installed for this Python. Install it first: $Python -m pip install pyarmor"
}

if (Test-Path $Out) {
    Remove-Item -LiteralPath $Out -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $OutScripts | Out-Null

# Keep the WebUI entry and public/default config readable. Obfuscate the
# implementation modules that contain routing, provider handling and tools.
Copy-Item -LiteralPath (Join-Path $Scripts "agent.py") -Destination $OutScripts
Copy-Item -LiteralPath (Join-Path $Root "agent_config.json") -Destination $Out

$Modules = @(
    "agent_chat.py",
    "agent_ui.py",
    "agent_config.py",
    "agent_tools.py",
    "agent_tools_common.py",
    "agent_tools_models.py",
    "agent_tools_image.py",
    "agent_tools_api.py",
    "agent_tools_video.py",
    "agent_tools_workspace.py",
    "agent_tools_schemas.py",
    "agent_tools_registry.py",
    "agent_prompts.py",
    "canva_mcp.py"
)

foreach ($Module in $Modules) {
    $Path = Join-Path $Scripts $Module
    if (Test-Path $Path) {
        & $Python -m pyarmor gen --output $OutScripts $Path
        if ($LASTEXITCODE -ne 0) {
            throw "PyArmor failed on $Module"
        }
    }
}

# Copy remaining plain modules (no secrets/core logic) so the build is complete.
Get-ChildItem -LiteralPath $Scripts -Filter *.py -File | ForEach-Object {
    if ($_.Name -eq "agent.py" -or $Modules -contains $_.Name) { return }
    Copy-Item -LiteralPath $_.FullName -Destination $OutScripts
    Write-Host "[Agent Protect] Copied plain module: $($_.Name)"
}

$Readme = @"
# sd-webui-agent protected build

This folder is generated by protect_agent_pyarmor.ps1.

- scripts/agent.py remains readable so Stable Diffusion WebUI can discover the extension.
- Core modules are obfuscated by PyArmor and loaded by the readable entry file.
- agent_config.json is copied with empty/default API keys. Do not publish real keys.

To use it, replace or package the sd-webui-agent extension folder with this generated folder.
"@

Set-Content -LiteralPath (Join-Path $Out "PROTECTED_BUILD_README.md") -Value $Readme -Encoding UTF8

Write-Host "[Agent Protect] Done."
Write-Host "[Agent Protect] Protected extension: $Out"
